### ISSUE TITLE
Running an docker-compose.yml file.

### ISSUE THREAD

**Issue by vgogov** [ddrozdov/docker-compose-swarm-mode#1]
Hello,

Thanks for writing this python script. I'm pretty new to python and having trouble running the docker_compose_swarm_mode.py on my docker-compose.yml file. I have all the python packages installed. If I execute the script I get the following:

usage: docker_compose_swarm_mode.py [-h] [-f FILE] [-p PROJECT_NAME] [--dry-run]
                                    {pull,rm,start,stop,up} ... [service [service ...]]
docker_compose_swarm_mode.py: error: too few arguments

Do I need to modify anything in the docker_compose_swarm_mode.py or just run that script against my docker-compose.yml file. Thanks!

**Comment by ddrozdov** [comment]
You should specify some command, e.g.:
`./docker_compose_swarm_mode.py up`
