### ISSUE TITLE
Feature Idea:  Dockerize

### ISSUE THREAD

**Issue by jritsema** [ddrozdov/docker-compose-swarm-mode#22]
Might be cool if you added a Dockerfile with a public build so that folks could run this CLI tool in a container by doing something like...

```
$ docker run -it --rm ddrozdov/docker-compose-swarm-mode
```

**Comment by Mehonoshin** [comment]
@jritsema can you describe any usecase for it?
Additionally such container should somehow have access to docker daemon API to run docker service commands. Looks too complicated.

**Comment by jritsema** [comment]
Ya, I'm just suggesting running the tool inside a container rather than having users have to worry about whether or not they have the correct version of python installed, running pip, etc.  Seems like you would just need the docker binary inside the container along with the docker env vars pointing to the engine host.  I'll see if I can put something together next week.

**Comment by ddrozdov** [comment]
Done.
You can run it like this:
`docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -v /some/dir/with/compose/files:/compose ddrozdov/docker-compose-swarm-mode -f /compose/docker-compose.yml --dry-run up`
