### ISSUE TITLE
unless-stopped restart condition error

### ISSUE THREAD

**Issue by the-nw1-group** [ddrozdov/docker-compose-swarm-mode#25]
I think I'm getting the following error:

``` python
Traceback (most recent call last):
  File "/home/wibble/docker_compose_swarm_mode.py", line 321, in <module>
    main()
  File "/home/wibble/docker_compose_swarm_mode.py", line 297, in main
    getattr(docker_compose, args.command)()
  File "/home/wibble/docker_compose_swarm_mode.py", line 179, in up
    locals().get(parameter, unsupported)()
  File "/home/wibble/docker_compose_swarm_mode.py", line 105, in restart
    cmd.extend(['--restart-condition', {'always': 'any'}[value], '\\\n'])
KeyError: 'unless-stopped'
```

because we have the following in our compose files:
`restart: unless-stopped`

**Comment by the-nw1-group** [comment]
OK - sorry, I see docker swarm service create doesn't support unless-stopped.

I see I have loads of work ahead to convert our compose file, to something suitable to use with docker swarm :-(

**Comment by ddrozdov** [comment]
Moreover there is no `stop` command for docker service.
What I do to "stop" the service is `scale` it to zero replicas. In this case `restart` "unless-stopped" and "always" would logically do the same so you can just change it to "always" in your configs.
