### ISSUE TITLE
What is the alternative to volumes_from?

### ISSUE THREAD

**Issue by vingrad** [ddrozdov/docker-compose-swarm-mode#3]
WARNING: unsupported parameter volumes_from

Output from 'docker-compose-swarm-mode':
`Running:
docker service create --with-registry-auth \
 --name dns_mysql-slave \
 --mount type=bind,src=/dns/mysql-slave.cnf,dst=/etc/mysql/my.cnf \
 --env MYSQL_ROOT_PASSWORD=XXXXXXX\
 --constraint 'node==worker2' \
 mysql

`

Sample: compose
`
  mysql-slave:
    image: mysql
    volumes_from:
      - data-slave
    volumes:
      - /dns/mysql-slave.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXX
      - "constraint:node==worker2"
    network_mode: dns

  data-slave:
    image: busybox:latest
    volumes:
      - /var/lib/mysql
    network_mode: dns
    environment:
      - "constraint:node==worker1"

`

**Comment by ddrozdov** [comment]
`docker service` doesn't support `volumes_from` and AFAIK is not going to support it.
You should use top-level volumes instead of data containers.

E.g. (from docker-compose [docs](https://docs.docker.com/compose/compose-file/#/version-2)):

```
version: '2'
services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
```
