### ISSUE TITLE
Support for variable substitution is missing

### ISSUE THREAD

**Issue by arkadius** [ddrozdov/docker-compose-swarm-mode#33]
Regards to this: https://docs.docker.com/compose/compose-file/#/variable-substitution

**Comment by ddrozdov** [comment]
Why do you think it is missing?
If you pass some env variables to the script, they would be used on `docker service` invocation.

**Comment by arkadius** [comment]
I'm not sure if I understand your point. If you have in your docker-compose.yml:

```
command: external.host=${EXT_HOST}
```

And then running:

```
EXT_HOST=foobar.com docker-compose-swarm-mode up
```

... foobar.com won't be replaced in place of ${EXT_HOST} because neither docker-compose-swarm-mode nor docker will handle it. Regards to docker-compose, there is https://github.com/docker/compose/blob/master/compose/config/interpolation.py module responsible for it

**Comment by ddrozdov** [comment]
These variables are replaced not by docker-compose-swarm-mode, but by OS shell when docker-compose-swarm-mode executes `docker service` command.
If you run the script with `--dry-run` they won't be replaced, but without `--dry-run` they will be.

**Comment by arkadius** [comment]
Ok I got it. I must try it again. Maybe there was other problem with my upper level ansible script which invoked dcsm
