### ISSUE TITLE
pip install, how do you run it ?

### ISSUE THREAD

**Issue by purplefish32** [ddrozdov/docker-compose-swarm-mode#4]
Sorry for the totaly noob question, I have installed the script via pip, but how do you run it ?

"docker-compose-swarm-mode" just gives me "zsh: command not found: docker-compose-swarm-mode"

**Comment by ddrozdov** [comment]
It should've been installed in `/usr/local/bin/`
Usually this dir is listed in the PATH environment variable so running the script using just `docker-compose-swarm-mode` works fine.

Does `/usr/local/bin/docker-compose-swarm-mode` file exist on your system?

**Comment by purplefish32** [comment]
No the file is not present in /usr/local/bin/

pip seems to have installed docker-compose-swarm-mode, but I have no idea where :)

if I rerun the pip install command I get the following : 

``` bash
Requirement already satisfied (use --upgrade to upgrade): docker-compose-swarm-mode in /home/donovan/.local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): yodl>=1.0.0 in /home/donovan/.local/lib/python2.7/site-packages (from docker-compose-swarm-mode)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.09 in /home/donovan/.local/lib/python2.7/site-packages (from yodl>=1.0.0->docker-compose-swarm-mode)
```

The system is an Ubuntu 16.04

**Comment by ddrozdov** [comment]
It looks like you've run `pip` under your user, not under `root`. So the script hasn't been installed system-wide. In this case I have no idea where to find it too :)

Please install it once again using `sudo pip ...`

**Comment by purplefish32** [comment]
[faceplam]

Thanks, Now it works, I needed the -H flag though

``` bash
sudo -H pip install docker-compose-swarm-mode
```
