### ISSUE TITLE
'int' object has no attribute 'replace'

### ISSUE THREAD

**Issue by sekhrivijay** [ddrozdov/docker-compose-swarm-mode#45]
Running the script with a compose file that has port like this
ports:
            - 2181

yields exception 
`Traceback (most recent call last):
  File "./docker_compose_swarm_mode.py", line 548, in <module>
    main()
  File "./docker_compose_swarm_mode.py", line 518, in main
    getattr(docker_compose, args.command)()
  File "./docker_compose_swarm_mode.py", line 214, in up
    locals().get(parameter, unsupported)()
    up_parser.add_argument('-d', help='docker-compose compatibility; ignored', action='store_true')
  File "./docker_compose_swarm_mode.py", line 166, in ports
    add_flag('--publish', port)
  File "./docker_compose_swarm_mode.py", line 112, in add_flag
    cmd.extend([key, shellquote(value), '\\\n'])
  File "./docker_compose_swarm_mode.py", line 545, in shellquote
    return "'" + s.replace("'", "'\\''") + "'"`

As workaround I fixed it on line 544 by casting it into str 

`return "'" + str(s).replace("'", "'\\''") + "'"`

Great work BTW . At least this can be used as a workaround for the time being

**Comment by ddrozdov** [comment]
According to the examples in the [docs](https://docs.docker.com/compose/compose-file/#/ports), the port should be specified in the quotes. That way it would be parsed as a string.
Does the official docker-compose work well with the port without the quotes?
