### ISSUE TITLE
Support for docker-compose environment file

### ISSUE THREAD

**Issue by kinghuang** [ddrozdov/docker-compose-swarm-mode#5]
Docker Compose supports declaring environment variables, including CLI environment variables, in a .env file. It would be useful to support this in docker-compose-swarm-mode.

[Environment file](https://docs.docker.com/compose/env-file/)

**Comment by ddrozdov** [comment]
Never heard about that `.env` file before. I'll try to support it.
By the way, [variable substitution](https://docs.docker.com/compose/compose-file/#variable-substitution) using the shell environment in which `docker-compose-swarm-mode` is run, is already supported.

**Comment by kinghuang** [comment]
Thanks @ddrozdov! I'll make the changes and submit a pull request, if you haven't already started on it.

**Comment by ddrozdov** [comment]
I haven't started yet, so a PR is very welcome, thanks.

**Comment by kinghuang** [comment]
PR #11 submitted. Note that its base is PR #9.
